### ISSUE TITLE
`Shrine.storages[:cache].storage` unavailable

### ISSUE THREAD

**Issue by marckohlbrugge** [shrinerb/shrine-memory#2]
I'm using the `shrine-imgix` plugin in combination with S3 like so:

```ruby
imgix = Shrine::Storage::Imgix.new(
  storage:          Shrine::Storage::S3.new(**s3_options),
  include_prefix:   true, # set to false if you have prefix configured in Imgix source
  api_key:          "xzy123",                 #
  host:             "my-subdomain.imgix.net", # Imgix::Client options
  secure_url_token: "abc123", # optional      #
)

Shrine.storages[:store] = imgix
```

I'm also using direct uploads with the `presign_endpoint` plugin.

As part of the upload process I show the user a preview of the image they are uploading, before they submit the form. I generate the URL of this image using the following code:

```ruby
path = []
path << Shrine.storages[:cache].storage.prefix
path << File.basename(params[:key])
path = path.join("/")
imgix = Shrine.storages[:cache].client
url = imgix.path(path).to_url(w: 125, h: 125, dpr: 2, fit: "crop")
```

For my tests I want to use `shrine-memory`, but the above URL generation code relies on the `Shrine.storages[:cache].storage` method which isn't available in `shrine-memory`.

Is there a workaround for this using this gem? I don't need an actual working URL obviously, but ideally `shrine-memory` would be able to mimic's `shrine-imgix` interface.

**Comment by marckohlbrugge** [comment]
It looks like I can wrap `Shrine::Storage::Memory` with `Shrine::Storage::Imgix.new` like I'd do normally so `.storage` becomes available. However, I still cannot use `Shrine.storages[:cache].storage.prefix` as the `Shrine::Storage::Memory` instance does not have a prefix method.

**Comment by marckohlbrugge** [comment]
After further exploration it seems like `prefix` is something specific to the S3 storage, as are a bunch of other attributes. It's probably outside of `shrine-memory`'s scope to support all possible attributes any storage plugin might have.

We could add support for any arbitrary attribute, but even that is probably outside of its scope and is better left as something part of one's testing suite. (e.g. mocking with rspec)

If you agree we can close this issue.

**Comment by janko** [comment]
I would really like to change `shrine-imgix` to provide a _plugin_ instead of a storage, I think a storage was the wrong abstraction layer. I will try to make this change in the next couple of days.

I will close this issue as it's not related to the `shrine-memory` gem.

**Comment by janko** [comment]
I'll also make it optional for storage to respond to `#prefix`.

**Comment by janko** [comment]
`shrine-imgix` 0.5.0 has been released with the implementation rewritten as a plugin, I recommend switching to it when you have the chance, it's much cleaner. There I've also made it optional for storage to have a `#prefix` method.

**Comment by marckohlbrugge** [comment]
Thanks! Using 0.5.0 now in production 🙌✨
